# test script generated by AI

import matplotlib.pyplot as plt
from my_utility import parse_gt_file, prepare_data, augment_data
from PIL import ImageDraw

# Paths to test files
gt_file_path = 'project_3\\MOT16-02\\gt\\gt.txt'  # Path to the MOTS ground truth file
image_folder = 'project_3\\MOT16-02\\img1'  # Path to the folder containing images


# Load and parse the ground truth data
gt_data = parse_gt_file(gt_file_path)

# Get unique frame IDs from the ground truth data
frame_ids = sorted(set(obj['frame_id'] for obj in gt_data))
# Loop through each frame ID
for frame_id in frame_ids:
    # Load image, bounding boxes, and labels
    image, boxes, _ = prepare_data(gt_data, image_folder, frame_id)  # Unpack all three, ignore labels

    # Display original image with bounding boxes
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))

    # Draw bounding boxes on the original image
    draw = ImageDraw.Draw(image)
    for box in boxes:
        # Ensure each box has exactly four elements (xmin, ymin, xmax, ymax)
        if len(box) == 4:
            draw.rectangle([box[0], box[1], box[2], box[3]], outline="red", width=2)
        else:
            print(f"Unexpected box format: {box}")  # Debugging print if format is incorrect

    # Plot the original image
    ax[0].imshow(image)
    ax[0].set_title(f"Original Image with Bounding Boxes - Frame {frame_id}")

    # Apply augmentation
    augmented_image = augment_data(image)

    # Draw bounding boxes on augmented image
    draw_aug = ImageDraw.Draw(augmented_image)
    for box in boxes:
        if len(box) == 4:
            draw_aug.rectangle([box[0], box[1], box[2], box[3]], outline="blue", width=2)
        else:
            print(f"Unexpected box format in augmented image: {box}")  # Debugging print if format is incorrect

    # Plot the augmented image
    ax[1].imshow(augmented_image)
    ax[1].set_title(f"Augmented Image with Bounding Boxes - Frame {frame_id}")

    plt.show()

    # Optional: Add a pause or wait for a key press to move to the next frame
    input("Press Enter to continue to the next frame...")
